###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    myhome-db:
      image: postgres:9.6-alpine
      container_name: myhome-db-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=myhome
      ports:
          - "5432:5432"
    myhome-webserver:
      image: nginx:alpine
      container_name: myhome-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/myhome-webserver/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - "8080:80"
      expose:
          - "8080"
      environment:
          - VIRTUAL_HOST=myhome.local 
    myhome-php-fpm:
      build: docker/myhome-php-fpm
      container_name: myhome-php-fpm
      working_dir: /application
      environment:
        - LC_ALL=C.UTF-8 
        - LANG=C.UTF-8
      volumes:
        - .:/application
        - ./docker/myhome-php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    myhome-proxy:
      image: jwilder/nginx-proxy
      container_name: myhome-proxy
      ports:
          - "80:80"
      links:
          - myhome-webserver
      volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro     
