# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    purifier:
        config:
            pro:
                level_map:
                    quiet: 0
                    very-low: 1
                    low: 3
                    medium-low: 5
                    medium: 7
                    medium-high: 9
                    high: 11
                    very-high: 13
                    almost-max: 15
                    max: 17
        general: 
            delay: 3
            period: 60
        devices:
            - {
                scenario: 'default', 
                model: 'pro',
                adapter: '\App\Service\Purifier\PythonMiio\PythonMiioAdapter',  
                payload: { 
                    ip: '192.168.8.153',
                    token: '299db5c1f69101a1b1d061f3bc78de19'
                }
                }
            - {
                scenario: 'default', 
                model: 'pro',
                adapter: '\App\Service\Purifier\PythonMiio\PythonMiioAdapter',  
                payload: { 
                    ip: '192.168.8.155',
                    token: 'fd523a885c53215dd830b76b46cbe919'
                }
                }
        scenarios:
            default:
                increasing:
                    - { pollution: '0',  level: 'quiet' } 
                    - { pollution: '3',  level: 'very-low' }
                    - { pollution: '5',  level: 'low' }
                    - { pollution: '7',  level: 'medium-low' }
                    - { pollution: '10', level: 'medium' }
                    - { pollution: '13', level: 'medium-high' }
                    - { pollution: '15', level: 'high' }   
                    - { pollution: '18', level: 'very-high' }                       
                    - { pollution: '22', level: 'almost-max' }
                    - { pollution: '25', level: 'max' }                    
                decreasing:
                    - { pollution: '5',  level: 'low' }
                    - { pollution: '3',  level: 'quiet' }                    
                    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
